### ISSUE TITLE
Why are some classes and categories (like _UXButton) missing from this repo?

### ISSUE THREAD

**Issue by NSExceptional** [hbang/UXKit-Headers#1]
`_UXButton` defines a few new methods, I don't see why it could have been removed. Looks like a lot else was removed too, like nearly all of the important `NSView` categories.

**Comment by kirb** [comment]
It's explained in [the readme](https://github.com/hbang/UXKit-Headers/blob/master/README.md). These are hand-written only as I've needed. If you want dumped headers, look elsewhere.

**Comment by NSExceptional** [comment]
Oh, it didn't hit me that you probably just haven't been using those categories or classes yet. I'll submit a PR with some additions at some point. 😅
